def get_numbers(number):
    """
    Each new term in the Fibonacci sequense is generated by adding the previous two terms. By starting with 1 and 2, the first 10 term will be:
    1,2,3,5,8,13,21,34,55,89
    By considering the terms in the Fibonacci sequense whose values do not exceed four million, find the sum of the even-valued terms
    """    
    if number == 0:
        return 1
    if number == 1:
        return 2
    else:
        return get_numbers(number - 1) + get_numbers(number - 2)


tot = 0
number = 0

while get_numbers(number) <= 4000000:
    if get_numbers(number) % 2 == 0:
        tot += get_numbers(number)
    
    number += 1

print(tot, number)